# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

na_approx <- function(v) {
    .Call(`_microclimdata_na_approx`, v)
}

splineCpp <- function(daily_values) {
    .Call(`_microclimdata_splineCpp`, daily_values)
}

napproxCpp <- function(pai, landcover, lpai) {
    .Call(`_microclimdata_napproxCpp`, pai, landcover, lpai)
}

uniquecpp <- function(matrix) {
    .Call(`_microclimdata_uniquecpp`, matrix)
}

meanpai <- function(pai, landcover) {
    .Call(`_microclimdata_meanpai`, pai, landcover)
}

whichcpp <- function(v, x) {
    .Call(`_microclimdata_whichcpp`, v, x)
}

fillpai <- function(pai, landcover) {
    .Call(`_microclimdata_fillpai`, pai, landcover)
}

expectedpai <- function(landcover, landcoverm, pai) {
    .Call(`_microclimdata_expectedpai`, landcover, landcoverm, pai)
}

seasoneffect <- function(lai) {
    .Call(`_microclimdata_seasoneffect`, lai)
}

seasonadjCpp <- function(lai, seffect) {
    .Call(`_microclimdata_seasonadjCpp`, lai, seffect)
}

juldayCpp <- function(year, month, day) {
    .Call(`_microclimdata_juldayCpp`, year, month, day)
}

hourlytempv <- function(tmn, tmx, year, month, day, lat, lon, srte = 0.09) {
    .Call(`_microclimdata_hourlytempv`, tmn, tmx, year, month, day, lat, lon, srte)
}

converthumidityCpp <- function(sph, tc, pk) {
    .Call(`_microclimdata_converthumidityCpp`, sph, tc, pk)
}

airMass <- function(Z, z = 0.0) {
    .Call(`_microclimdata_airMass`, Z, z)
}

dirtran <- function(Z, TL, z = 0) {
    .Call(`_microclimdata_dirtran`, Z, TL, z)
}

diftran <- function(Z, TL) {
    .Call(`_microclimdata_diftran`, Z, TL)
}

extrarad <- function(jd) {
    .Call(`_microclimdata_extrarad`, jd)
}

Linkev <- function(sh, pk, aod) {
    .Call(`_microclimdata_Linkev`, sh, pk, aod)
}

clearskyradv <- function(year, month, day, hr, lat, lon, z, TL) {
    .Call(`_microclimdata_clearskyradv`, year, month, day, hr, lat, lon, z, TL)
}

clearskyradhourly <- function(year, month, day, hr, lat, lon, z, TL) {
    .Call(`_microclimdata_clearskyradhourly`, year, month, day, hr, lat, lon, z, TL)
}

difpropvCpp <- function(swrad, year, month, day, hr, lat, lon) {
    .Call(`_microclimdata_difpropvCpp`, swrad, year, month, day, hr, lat, lon)
}

tempsix <- function(tc) {
    .Call(`_microclimdata_tempsix`, tc)
}

prectohour <- function(prec) {
    .Call(`_microclimdata_prectohour`, prec)
}

blendtempCpp <- function(tasmin, tasmax, temp) {
    .Call(`_microclimdata_blendtempCpp`, tasmin, tasmax, temp)
}

applytodaily <- function(hourly, func) {
    .Call(`_microclimdata_applytodaily`, hourly, func)
}

blendprecCpp <- function(precd, prech) {
    .Call(`_microclimdata_blendprecCpp`, precd, prech)
}

satvapCpp <- function(tc) {
    .Call(`_microclimdata_satvapCpp`, tc)
}

clearskya <- function(year, month, day, hr, lats, lons) {
    .Call(`_microclimdata_clearskya`, year, month, day, hr, lats, lons)
}

na_fill_matrix <- function(m, pw = 2.0) {
    .Call(`_microclimdata_na_fill_matrix`, m, pw)
}

ordered_cells <- function(mat, i, j, pw) {
    .Call(`_microclimdata_ordered_cells`, mat, i, j, pw)
}

slicearray <- function(a, d1, d2, d3, k) {
    .Call(`_microclimdata_slicearray`, a, d1, d2, d3, k)
}

na_fill_array <- function(clima, lsea, pw = 2.0) {
    .Call(`_microclimdata_na_fill_array`, clima, lsea, pw)
}

expandssttohour <- function(sst) {
    .Call(`_microclimdata_expandssttohour`, sst)
}

remove_nas <- function(v) {
    .Call(`_microclimdata_remove_nas`, v)
}

calculate_mode <- function(x) {
    .Call(`_microclimdata_calculate_mode`, x)
}

modalwinddir <- function(wd) {
    .Call(`_microclimdata_modalwinddir`, wd)
}

mattoarray <- function(m, n) {
    .Call(`_microclimdata_mattoarray`, m, n)
}

solarindexarray <- function(year, month, day, hour, lats, lons) {
    .Call(`_microclimdata_solarindexarray`, year, month, day, hour, lats, lons)
}

applymeanCpp <- function(a) {
    .Call(`_microclimdata_applymeanCpp`, a)
}

temptoday <- function(tc) {
    .Call(`_microclimdata_temptoday`, tc)
}

rhtoday <- function(rh, tc) {
    .Call(`_microclimdata_rhtoday`, rh, tc)
}

lwtoday <- function(lwdown, tc) {
    .Call(`_microclimdata_lwtoday`, lwdown, tc)
}

tmnmxtodtr <- function(tmn, tmx) {
    .Call(`_microclimdata_tmnmxtodtr`, tmn, tmx)
}

sphtoea <- function(sph, pk) {
    .Call(`_microclimdata_sphtoea`, sph, pk)
}

netshorttodownshort <- function(rss, alb) {
    .Call(`_microclimdata_netshorttodownshort`, rss, alb)
}

netlwtoskyem <- function(rsl, tmx, tmn) {
    .Call(`_microclimdata_netlwtoskyem`, rsl, tmx, tmn)
}

uvtows <- function(u, v) {
    .Call(`_microclimdata_uvtows`, u, v)
}

rainadjustm <- function(rainm, rrain, rfrac, rtot) {
    .Call(`_microclimdata_rainadjustm`, rainm, rrain, rfrac, rtot)
}

rangelimapply <- function(v1, v2, v3, v3c, rangelim = 1.05) {
    .Call(`_microclimdata_rangelimapply`, v1, v2, v3, v3c, rangelim)
}

prangelimapply <- function(v1, v2, v3, v3c, rangelim = 1.05) {
    .Call(`_microclimdata_prangelimapply`, v1, v2, v3, v3c, rangelim)
}

tempha <- function(tmean, dtr, year, month, day, lats, lons, srte = 0.09) {
    .Call(`_microclimdata_tempha`, tmean, dtr, year, month, day, lats, lons, srte)
}

splina <- function(a) {
    .Call(`_microclimdata_splina`, a)
}

relhuma <- function(ea, tch) {
    .Call(`_microclimdata_relhuma`, ea, tch)
}

dailyclm <- function(year, month, day, lats) {
    .Call(`_microclimdata_dailyclm`, year, month, day, lats)
}

dailycla <- function(csr, cols) {
    .Call(`_microclimdata_dailycla`, csr, cols)
}

hourlyclm <- function(year, month, day, lats) {
    .Call(`_microclimdata_hourlyclm`, year, month, day, lats)
}

hourlycla <- function(year, month, day, lats, lons) {
    .Call(`_microclimdata_hourlycla`, year, month, day, lats, lons)
}

hourlydifa <- function(swrad, year, month, day, lats, lons) {
    .Call(`_microclimdata_hourlydifa`, swrad, year, month, day, lats, lons)
}

lwrada <- function(skyem, tch) {
    .Call(`_microclimdata_lwrada`, skyem, tch)
}

precha <- function(precd) {
    .Call(`_microclimdata_precha`, precd)
}

coastexpm <- function(coastm, n) {
    .Call(`_microclimdata_coastexpm`, coastm, n)
}

coastexpa <- function(winddir, coastexp, n = 8L) {
    .Call(`_microclimdata_coastexpa`, winddir, coastexp, n)
}

apply3D <- function(a) {
    .Call(`_microclimdata_apply3D`, a)
}

find_pai <- function(ndvi) {
    .Call(`_microclimdata_find_pai`, ndvi)
}

leafrcpp <- function(lref, pai, gref, x, albin) {
  .Call(`_microclimdata_leafrcpp`, lref, pai, gref, x, albin)
}

solve_gref <- function(lref, pai, x, albin, tol = 1e-6, max_iter = 100L) {
  .Call(`_microclimdata_solve_gref`, lref, pai, x, albin, tol, max_iter)
}

find_gref <- function(lref, pai, x, albin) {
    .Call(`_microclimdata_find_gref`, lref, pai, x, albin)
}

find_lref <- function(pai, gref, x, albin) {
    .Call(`_microclimdata_find_lref`, pai, gref, x, albin)
}

getsoiltypecpp <- function(bulkden, clay, sand, silt) {
    .Call(`_microclimdata_getsoiltypecpp`, bulkden, clay, sand, silt)
}

calcclumpcppone <- function(leafd, hgt, lai, n) {
    .Call(`_microclimdata_calcclumpcppone`, leafd, hgt, lai, n)
}

calcclumpcpp <- function(leafd, hgt, lai, mx = 0.48) {
    .Call(`_microclimdata_calcclumpcpp`, leafd, hgt, lai, mx)
}

